name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#fffeff"
    - "#1d191f"
    - "#668d79"
    - "#bfb2e4"
    - "#a200b2"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
